-- =============================================================================
-- BOH ERP — HERO SCHEMA (consolidated 0001 → 0013, final state)
--
-- A single, idempotent, dependency-ordered script that builds the ENTIRE
-- database from an empty Supabase project. Every later fix is already baked in:
--   * is_admin() / current_location_id() are SECURITY DEFINER (no RLS recursion)
--   * location_id is NOT NULL on every operational table from the start
--   * recipe_ingredients supports SUB-RECIPES (XOR raw_material/sub_recipe)
--   * inventory_ledger has SALES_DEPLETION + source_ref idempotency
--   * pos_sales / unmapped_sales carry (order_id, line_no) idempotency keys
--   * recipe_cogs() compounds sub-recipe overhead; recipe_costing uses LATERAL
--
-- Philosophy: transactional ledger. Balances are NEVER stored — they are derived
-- through VIEWS. inventory_ledger / vendor_payments are APPEND-ONLY (enforced by
-- the prevent_mutation trigger). Multi-tenant: every row is scoped to location_id
-- and RLS isolates tenants via current_location_id().
--
-- HOW TO RUN: paste into the Supabase SQL Editor on a CLEAN database and run once.
-- Safe to re-run (idempotent). Edit the v_admin_email in SECTION 12 first.
-- =============================================================================

create extension if not exists pgcrypto;

-- =============================================================================
-- SECTION 1: TENANCY — organizations → locations
-- =============================================================================
create table if not exists public.organizations (
  id          uuid        primary key default gen_random_uuid(),
  name        varchar(255) not null,
  created_at  timestamptz not null default now()
);

create table if not exists public.locations (
  id                    uuid        primary key default gen_random_uuid(),
  organization_id       uuid        not null references public.organizations (id) on delete cascade,
  name                  varchar(255) not null,
  google_spreadsheet_id text,
  pos_webhook_secret    text,            -- per-tenant Petpooja webhook secret
  petpooja_rest_id      text,            -- Petpooja Get-Orders mapping code (per outlet)
  pos_commissions       jsonb       not null default '{}'::jsonb,  -- {"Swiggy":25,"Zomato":22}
  pos_last_synced_at    timestamptz,
  petpooja_app_key      text,            -- per-outlet Petpooja creds (SECRET — no authenticated grant)
  petpooja_app_secret   text,
  petpooja_access_token text,
  created_at            timestamptz not null default now()
);
create index if not exists idx_locations_org on public.locations (organization_id);

-- =============================================================================
-- SECTION 2: CORE OPERATIONAL TABLES (location_id NOT NULL from the start)
-- =============================================================================

-- profiles — mirrors auth.users. roles INT[]: 1=Admin 2=Manager 3=Store 4=Kitchen
create table if not exists public.profiles (
  id          uuid        primary key references auth.users (id) on delete cascade,
  full_name   varchar(255),
  roles       int[]       not null default array[3]::int[],
  location_id uuid        not null references public.locations (id) on delete cascade,
  created_at  timestamptz not null default now()
);
create index if not exists idx_profiles_location on public.profiles (location_id);

-- departments — IDENTITY ids (collision-free across locations), name unique per location.
create table if not exists public.departments (
  id          int          generated by default as identity primary key,
  name        varchar(100) not null,
  location_id uuid         not null references public.locations (id) on delete cascade,
  constraint departments_location_id_name_key unique (location_id, name)
);
create index if not exists idx_departments_location on public.departments (location_id);

-- vendors
create table if not exists public.vendors (
  id              uuid        primary key default gen_random_uuid(),
  vendor_code     varchar(50) not null,
  name            varchar(255) not null,
  contact_person  varchar(255),
  phone           varchar(20),
  email           varchar(255),
  bank_name       varchar(255),
  account_number  varchar(50),
  ifsc_code       varchar(20),
  nature_of_supply varchar(255),
  alt_phone        varchar(20),
  category         varchar(100),
  upi_id           varchar(255),
  payment_terms    varchar(100),
  address          text,
  gstin            varchar(20),
  notes            text,
  dormancy_note    text,
  status          varchar(20) not null default 'ACTIVE'
                    check (status in ('ACTIVE', 'INACTIVE', 'BLACKLISTED')),
  approved        boolean     not null default false,
  approved_at     timestamptz,
  approved_by     uuid        references public.profiles (id) on delete set null,
  location_id     uuid        not null references public.locations (id) on delete cascade,
  created_at      timestamptz not null default now(),
  constraint vendors_location_id_vendor_code_key unique (location_id, vendor_code)
);
create index if not exists idx_vendors_location on public.vendors (location_id);

-- raw_materials
create table if not exists public.raw_materials (
  id                 uuid          primary key default gen_random_uuid(),
  name               varchar(255)  not null,
  brand              varchar(255),
  purchase_unit      varchar(50)   not null,
  stock_unit         varchar(50)   not null,
  conversion_factor  numeric(14,4) not null default 1 check (conversion_factor > 0),
  par_level          numeric(14,4) not null default 0 check (par_level >= 0),
  vendor_id          uuid          references public.vendors (id) on delete set null,
  category           varchar(100),
  needs_review       boolean       not null default false,
  location_id        uuid          not null references public.locations (id) on delete cascade,
  created_at         timestamptz   not null default now()
);
create index if not exists idx_raw_materials_location on public.raw_materials (location_id);

-- recipes
create table if not exists public.recipes (
  id                  uuid          primary key default gen_random_uuid(),
  name                varchar(255)  not null,
  selling_price       numeric(14,2) not null default 0 check (selling_price >= 0),
  yield_portions      int           not null default 1 check (yield_portions > 0),
  overhead_percentage numeric(6,2)  not null default 0 check (overhead_percentage >= 0),
  category            varchar(100),
  pos_item_code       varchar(80),  -- maps an external POS SKU → this recipe
  department_id       int           references public.departments (id) on delete set null,
  location_id         uuid          not null references public.locations (id) on delete cascade,
  created_at          timestamptz   not null default now()
);
create index if not exists idx_recipes_location on public.recipes (location_id);
create index if not exists idx_recipes_pos_item_code on public.recipes (pos_item_code);
create index if not exists idx_recipes_department on public.recipes (department_id);
-- POS code unique WITHIN a location (two tenants may reuse the same SKU).
create unique index if not exists uq_recipes_location_pos_item_code
  on public.recipes (location_id, pos_item_code) where pos_item_code is not null;

-- recipe_ingredients — a row is EITHER a raw-material line OR a sub-recipe line.
create table if not exists public.recipe_ingredients (
  id               uuid          primary key default gen_random_uuid(),
  recipe_id        uuid          not null references public.recipes (id) on delete cascade,
  raw_material_id  uuid          references public.raw_materials (id) on delete restrict,
  sub_recipe_id    uuid          references public.recipes (id) on delete restrict,
  quantity_needed  numeric(14,4) not null check (quantity_needed > 0),
  location_id      uuid          not null references public.locations (id) on delete cascade,
  -- exactly one of {raw_material_id, sub_recipe_id} is set
  constraint recipe_ingredients_kind_chk check (num_nonnulls(raw_material_id, sub_recipe_id) = 1),
  -- a recipe may not be its own sub-recipe (deeper cycles guarded in app + recipe_cogs)
  constraint recipe_ingredients_no_self_subrecipe_chk
    check (sub_recipe_id is null or sub_recipe_id <> recipe_id),
  -- non-partial unique → valid ON CONFLICT arbiter for the sheet-pull upsert.
  -- NULL raw_material_id (sub-recipe lines) are DISTINCT, so they never collide.
  constraint recipe_ingredients_recipe_material_key unique (recipe_id, raw_material_id)
);
create index if not exists idx_recipe_ingredients_recipe on public.recipe_ingredients (recipe_id);
create index if not exists idx_recipe_ingredients_sub_recipe on public.recipe_ingredients (sub_recipe_id);
-- one sub-recipe line per (recipe, sub-recipe)
create unique index if not exists uq_recipe_ingredients_subrecipe
  on public.recipe_ingredients (recipe_id, sub_recipe_id) where sub_recipe_id is not null;

-- inventory_ledger — immutable. Convention: credits to_department, debits from_department.
create table if not exists public.inventory_ledger (
  id                  uuid          primary key default gen_random_uuid(),
  raw_material_id     uuid          not null references public.raw_materials (id) on delete restrict,
  from_department_id  int           references public.departments (id) on delete restrict,
  to_department_id    int           references public.departments (id) on delete restrict,
  vendor_id           uuid          references public.vendors (id) on delete restrict,
  type                varchar(40)   not null
                        constraint inventory_ledger_type_check check (type in (
                          'PURCHASE',
                          'ISSUE_TO_KITCHEN',
                          'INTER_DEPARTMENT_TRANSFER',
                          'MANUAL_SALE',
                          'WASTAGE',
                          'VARIANCE_RECONCILIATION',
                          'SALES_DEPLETION'
                        )),
  quantity            numeric(14,4) not null,
  unit_price          numeric(14,4),
  wastage_reason      varchar(255),
  created_by          uuid          references public.profiles (id) on delete set null,
  source_ref          text,         -- POS order id for SALES_DEPLETION idempotency
  transaction_date    date,         -- business/invoice date (backdated purchases); falls back to created_at
  location_id         uuid          not null references public.locations (id) on delete cascade,
  created_at          timestamptz   not null default now(),
  -- NULLs are DISTINCT, so legacy/non-POS rows never collide; two SALES_DEPLETION
  -- rows for the same (location, order, material) cannot both exist (retry-safe).
  constraint uq_inventory_ledger_source_ref unique (location_id, source_ref, raw_material_id)
);
create index if not exists idx_ledger_raw_material on public.inventory_ledger (raw_material_id);
create index if not exists idx_ledger_type         on public.inventory_ledger (type);
create index if not exists idx_ledger_from_dept     on public.inventory_ledger (from_department_id);
create index if not exists idx_ledger_to_dept       on public.inventory_ledger (to_department_id);
create index if not exists idx_ledger_vendor        on public.inventory_ledger (vendor_id);
create index if not exists idx_ledger_location      on public.inventory_ledger (location_id);

-- manual_sales_log — insert explodes the recipe into MANUAL_SALE ledger rows.
create table if not exists public.manual_sales_log (
  id            uuid        primary key default gen_random_uuid(),
  recipe_id     uuid        not null references public.recipes (id) on delete restrict,
  quantity_sold int         not null check (quantity_sold > 0),
  sale_date     date        not null default current_date,
  location_id   uuid        not null references public.locations (id) on delete cascade,
  created_at    timestamptz not null default now()
);
create index if not exists idx_manual_sales_date     on public.manual_sales_log (sale_date);
create index if not exists idx_manual_sales_location on public.manual_sales_log (location_id);

-- vendor_payments — append-only.
create table if not exists public.vendor_payments (
  id             uuid          primary key default gen_random_uuid(),
  vendor_id      uuid          not null references public.vendors (id) on delete restrict,
  amount_paid    numeric(14,2) not null check (amount_paid > 0),
  payment_mode   varchar(50)   not null,
  reference_utr  varchar(100),
  payment_date   date          not null default current_date,
  location_id    uuid          not null references public.locations (id) on delete cascade,
  created_at     timestamptz   not null default now()
);
create index if not exists idx_vendor_payments_vendor   on public.vendor_payments (vendor_id);
create index if not exists idx_vendor_payments_location on public.vendor_payments (location_id);

-- dues — money owed TO the restaurant (advances / IOUs). Mutable (settled later).
create table if not exists public.dues (
  id              uuid          primary key default gen_random_uuid(),
  location_id     uuid          not null references public.locations (id) on delete cascade,
  person_name     varchar(255)  not null,
  amount          numeric(14,2) not null check (amount > 0),
  reason          text,
  linked_date     date,
  date_settled    date,
  settled_amount  numeric(14,2) not null default 0 check (settled_amount >= 0),
  settled_mode    varchar(50),
  notes           text,
  created_at      timestamptz   not null default now()
);
create index if not exists idx_dues_location on public.dues (location_id);

-- kitchen_production — prepared / sold / item-wastage per dish per dept per day.
create table if not exists public.kitchen_production (
  id              uuid          primary key default gen_random_uuid(),
  location_id     uuid          not null references public.locations (id) on delete cascade,
  department_id   int           references public.departments (id) on delete set null,
  recipe_id       uuid          not null references public.recipes (id) on delete restrict,
  production_date date          not null default current_date,
  prepared_qty    numeric(14,3) not null default 0 check (prepared_qty >= 0),
  sold_qty        numeric(14,3) not null default 0 check (sold_qty >= 0),
  wastage_qty     numeric(14,3) not null default 0 check (wastage_qty >= 0),
  notes           text,
  created_at      timestamptz   not null default now(),
  constraint uq_kitchen_production unique (location_id, department_id, recipe_id, production_date)
);
create index if not exists idx_kitchen_production_location on public.kitchen_production (location_id);

-- daily_sales_reconciliation
create table if not exists public.daily_sales_reconciliation (
  id                     uuid          primary key default gen_random_uuid(),
  date                   date          not null,
  dine_in_gross          numeric(14,2) not null default 0,
  zomato_gross           numeric(14,2) not null default 0,
  swiggy_gross           numeric(14,2) not null default 0,
  cash_collected         numeric(14,2) not null default 0,
  upi_collected          numeric(14,2) not null default 0,
  card_collected         numeric(14,2) not null default 0,
  aggregator_commissions numeric(14,2) not null default 0,
  actual_bank_deposit    numeric(14,2) not null default 0,
  location_id            uuid          not null references public.locations (id) on delete cascade,
  created_at             timestamptz   not null default now(),
  constraint daily_sales_reconciliation_location_id_date_key unique (location_id, date)
);
create index if not exists idx_recon_location on public.daily_sales_reconciliation (location_id);

-- petty_cash_expenses
create table if not exists public.petty_cash_expenses (
  id           uuid          primary key default gen_random_uuid(),
  amount       numeric(14,2) not null check (amount > 0),
  category     varchar(100)  not null,
  description  text,
  logged_by    uuid          references public.profiles (id) on delete set null,
  date         date          not null default current_date,
  location_id  uuid          not null references public.locations (id) on delete cascade,
  created_at   timestamptz   not null default now()
);
create index if not exists idx_petty_cash_location on public.petty_cash_expenses (location_id);

-- location_sheets — optional multi-sheet registry (purpose → spreadsheet id).
create table if not exists public.location_sheets (
  id                    uuid        primary key default gen_random_uuid(),
  location_id           uuid        not null references public.locations (id) on delete cascade,
  purpose               varchar(50) not null,
  google_spreadsheet_id text        not null,
  created_at            timestamptz not null default now(),
  unique (location_id, purpose)
);
create index if not exists idx_location_sheets_location on public.location_sheets (location_id);

-- profile_locations — outlets an Area Manager (role 5) covers beyond their home.
-- WRITABLE ONLY via the service role (no INSERT/UPDATE/DELETE policy or grant).
create table if not exists public.profile_locations (
  profile_id  uuid        not null references public.profiles (id) on delete cascade,
  location_id uuid        not null references public.locations (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (profile_id, location_id)
);
create index if not exists idx_profile_locations_profile  on public.profile_locations (profile_id);
create index if not exists idx_profile_locations_location on public.profile_locations (location_id);

-- =============================================================================
-- SECTION 3: ANALYTICS / POS TABLES
-- =============================================================================

-- unmapped_sales — POS lines whose code matched no recipe (triage queue).
create table if not exists public.unmapped_sales (
  id            uuid        primary key default gen_random_uuid(),
  location_id   uuid        not null references public.locations (id) on delete cascade,
  pos_item_code varchar(80),
  item_name     varchar(255),
  quantity      int         not null default 1 check (quantity > 0),
  order_id      text,
  line_no       int,
  raw_payload   jsonb,
  resolved      boolean     not null default false,
  created_at    timestamptz not null default now(),
  constraint uq_unmapped_sales_order_line unique (location_id, order_id, line_no)
);
create index if not exists idx_unmapped_sales_location on public.unmapped_sales (location_id);
create index if not exists idx_unmapped_sales_open
  on public.unmapped_sales (location_id, created_at desc) where resolved = false;

-- stock_counts — manager physical counts; the "actual" leg of TvA variance.
create table if not exists public.stock_counts (
  id              uuid          primary key default gen_random_uuid(),
  location_id     uuid          not null references public.locations (id) on delete cascade,
  department_id   int           not null references public.departments (id) on delete restrict,
  raw_material_id uuid          not null references public.raw_materials (id) on delete restrict,
  count_date      date          not null default current_date,
  system_qty      numeric(14,4) not null default 0,
  actual_qty      numeric(14,4) not null default 0,
  par_level       numeric(14,4) not null default 0,
  variance        numeric(14,4) generated always as (actual_qty - system_qty) stored,
  created_by      uuid          references public.profiles (id) on delete set null,
  created_at      timestamptz   not null default now(),
  unique (location_id, department_id, raw_material_id, count_date)
);
create index if not exists idx_stock_counts_location on public.stock_counts (location_id);
create index if not exists idx_stock_counts_loc_date on public.stock_counts (location_id, count_date desc);
create index if not exists idx_stock_counts_material on public.stock_counts (raw_material_id);

-- pos_sales — per-recipe portions-sold fact (Epic-3 source of truth).
create table if not exists public.pos_sales (
  id            uuid        primary key default gen_random_uuid(),
  location_id   uuid        not null references public.locations (id) on delete cascade,
  recipe_id     uuid        not null references public.recipes (id) on delete restrict,
  quantity      int         not null default 1 check (quantity > 0),
  pos_item_code varchar(80),
  order_id      text,
  line_no       int,
  sold_at       timestamptz not null default now(),
  raw_payload   jsonb,
  created_at    timestamptz not null default now(),
  constraint uq_pos_sales_order_line unique (location_id, order_id, line_no)
);
create index if not exists idx_pos_sales_location  on public.pos_sales (location_id);
create index if not exists idx_pos_sales_recipe     on public.pos_sales (recipe_id);
create index if not exists idx_pos_sales_loc_soldat on public.pos_sales (location_id, sold_at desc);

-- pos_orders — one row per Petpooja order (financial + channel facts; the line
-- items live in pos_sales). Populated by the daily PULL (lib/pos/petpooja-pull).
create table if not exists public.pos_orders (
  id                  uuid        primary key default gen_random_uuid(),
  location_id         uuid        not null references public.locations (id) on delete cascade,
  order_key           text        not null,  -- ${order_date}#${orderID}: stable across re-pulls
  pos_order_id        text,
  ref_id              text,
  online_order_id     text,
  order_type          text,                  -- Delivery / Dine In / Pick Up
  channel             text,                  -- order_from: Swiggy / Zomato / POS
  sub_order_type      text,
  payment_type        text,                  -- Online / Cash / UPI / Card ...
  custom_payment_type text,
  gross_amount        numeric(14,2) not null default 0,
  discount_amount     numeric(14,2) not null default 0,
  tax_amount          numeric(14,2) not null default 0,  -- GST
  round_off           numeric(14,2) not null default 0,
  net_amount          numeric(14,2) not null default 0,
  status              text,
  sold_at             timestamptz,
  order_date          date,
  raw_payload         jsonb,
  created_at          timestamptz not null default now(),
  constraint uq_pos_orders unique (location_id, order_key)
);
create index if not exists idx_pos_orders_loc_date   on public.pos_orders (location_id, order_date);
create index if not exists idx_pos_orders_loc_soldat on public.pos_orders (location_id, sold_at);
-- RLS enable + policy for pos_orders is in SECTION 4 (after current_location_ids
-- is defined, which the policy references).

-- =============================================================================
-- SECTION 4: TENANT HELPER FUNCTIONS (SECURITY DEFINER → no RLS recursion)
-- =============================================================================
create or replace function public.is_admin()
returns boolean language sql security definer set search_path = public stable as $$
  select exists (select 1 from public.profiles where id = auth.uid() and 1 = any (roles));
$$;

create or replace function public.current_location_id()
returns uuid language sql security definer set search_path = public stable as $$
  select location_id from public.profiles where id = auth.uid();
$$;

create or replace function public.current_org_id()
returns uuid language sql security definer set search_path = public stable as $$
  select organization_id from public.locations
  where id = (select location_id from public.profiles where id = auth.uid());
$$;

create or replace function public.set_location_id()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.location_id is null then
    new.location_id := public.current_location_id();
  end if;
  return new;
end;
$$;

grant execute on function public.is_admin() to authenticated;
grant execute on function public.current_location_id() to authenticated;
grant execute on function public.current_org_id() to authenticated;

-- Cross-outlet roles (5 = Area Manager, 6 = Owner) and read/write scope helpers.
create or replace function public.is_owner()
returns boolean language sql security definer set search_path = public stable as $$
  select exists (select 1 from public.profiles where id = auth.uid() and 6 = any (roles));
$$;

create or replace function public.can_manage_org()
returns boolean language sql security definer set search_path = public stable as $$
  select exists (
    select 1 from public.profiles
     where id = auth.uid() and (1 = any (roles) or 6 = any (roles))
  );
$$;

-- READ scope: Owner → whole org; Area Manager → home + assigned outlets;
-- everyone else (Admin/Manager/Store/Kitchen) → home only (unchanged behavior).
create or replace function public.current_location_ids()
returns setof uuid language plpgsql security definer set search_path = public stable as $$
declare
  v_uid   uuid := auth.uid();
  v_roles int[];
  v_home  uuid;
  v_org   uuid;
begin
  select roles, location_id into v_roles, v_home
    from public.profiles where id = v_uid;
  if v_roles is null then
    return;
  end if;
  if 6 = any (v_roles) then
    select organization_id into v_org from public.locations where id = v_home;
    return query select id from public.locations where organization_id = v_org;
    return;
  end if;
  if 5 = any (v_roles) then
    return query
      select v_home
      union
      select pl.location_id from public.profile_locations pl where pl.profile_id = v_uid;
    return;
  end if;
  return query select v_home;
end;
$$;

-- WRITE scope: home only — cross-outlet access is READ-ONLY.
create or replace function public.current_writable_location_ids()
returns setof uuid language sql security definer set search_path = public stable as $$
  select public.current_location_id();
$$;

grant execute on function public.is_owner()                       to authenticated;
grant execute on function public.can_manage_org()                 to authenticated;
grant execute on function public.current_location_ids()           to authenticated;

-- set_pos_config — admin-only writer for the outlet's Petpooja restID +
-- per-platform commissions (avoids a broad UPDATE grant on locations).
create or replace function public.set_pos_config(p_rest_id text, p_commissions jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare home uuid;
begin
  if not exists (
    select 1 from public.profiles
     where id = auth.uid() and (1 = any(roles) or 6 = any(roles))
  ) then
    raise exception 'Only administrators can change POS configuration';
  end if;
  home := public.current_location_id();
  if home is null then raise exception 'No home location for this account'; end if;
  update public.locations
     set petpooja_rest_id = nullif(btrim(p_rest_id), ''),
         pos_commissions  = coalesce(p_commissions, '{}'::jsonb)
   where id = home;
end $$;
revoke all on function public.set_pos_config(text, jsonb) from public;
grant execute on function public.set_pos_config(text, jsonb) to authenticated;

-- Per-outlet Petpooja creds vault. Secret columns (no authenticated grant);
-- written via this admin-only setter (blank field keeps the stored value), and
-- the UI can read only a boolean "configured" status, never the values.
create or replace function public.set_pos_creds(
  p_app_key text, p_app_secret text, p_access_token text)
returns void language plpgsql security definer set search_path = public as $$
declare home uuid;
begin
  if not exists (
    select 1 from public.profiles
     where id = auth.uid() and (1 = any(roles) or 6 = any(roles))
  ) then
    raise exception 'Only administrators can change POS credentials';
  end if;
  home := public.current_location_id();
  if home is null then raise exception 'No home location for this account'; end if;
  update public.locations set
    petpooja_app_key      = coalesce(nullif(btrim(p_app_key), ''),      petpooja_app_key),
    petpooja_app_secret   = coalesce(nullif(btrim(p_app_secret), ''),   petpooja_app_secret),
    petpooja_access_token = coalesce(nullif(btrim(p_access_token), ''), petpooja_access_token)
  where id = home;
end $$;
revoke all on function public.set_pos_creds(text, text, text) from public;
grant execute on function public.set_pos_creds(text, text, text) to authenticated;

create or replace function public.pos_has_location_creds()
returns boolean language sql security definer set search_path = public stable as $$
  select exists (
    select 1 from public.locations
     where id = public.current_location_id()
       and petpooja_app_key is not null
       and petpooja_app_secret is not null
       and petpooja_access_token is not null
  );
$$;
revoke all on function public.pos_has_location_creds() from public;
grant execute on function public.pos_has_location_creds() to authenticated;

-- pos_orders RLS (here, not with the table def, because the policy references
-- current_location_ids() which is defined just above).
alter table public.pos_orders enable row level security;
drop policy if exists pos_orders_select on public.pos_orders;
create policy pos_orders_select on public.pos_orders for select to authenticated
  using (location_id in (select public.current_location_ids()));

-- Two outlets must not claim the same Petpooja store (shared company creds +
-- duplicate restID would cross-ingest another restaurant's orders).
create unique index if not exists uq_locations_petpooja_rest_id
  on public.locations (petpooja_rest_id) where petpooja_rest_id is not null;
grant execute on function public.current_writable_location_ids()  to authenticated;

-- =============================================================================
-- SECTION 5: TRIGGER FUNCTIONS
-- =============================================================================

-- Auto-provision a profile on signup (only once the tenant location is known).
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_roles    int[];
  v_location uuid;
begin
  begin
    select array(select jsonb_array_elements_text(new.raw_user_meta_data -> 'roles')::int)
      into v_roles;
  exception when others then v_roles := null;
  end;
  -- Clamp to operational roles 1-4: cross-outlet roles 5/6 are NEVER granted at
  -- signup (service-role-only). user_metadata is client-writable — a self-signup
  -- must not be able to mint an Owner/Area Manager.
  v_roles := array(select r from unnest(coalesce(v_roles, '{}'::int[])) r where r between 1 and 4);
  if array_length(v_roles, 1) is null then
    v_roles := array[3]::int[];
  end if;

  begin
    v_location := (new.raw_user_meta_data ->> 'location_id')::uuid;
  exception when others then v_location := null;
  end;

  if v_location is not null then
    insert into public.profiles (id, full_name, roles, location_id)
    values (new.id, new.raw_user_meta_data ->> 'full_name', v_roles, v_location)
    on conflict (id) do nothing;
  end if;
  return new;
end;
$$;

-- Explode a manual sale's recipe into MANUAL_SALE ledger deductions from Kitchen.
create or replace function public.handle_manual_sale()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_kitchen_id int;
begin
  select id into v_kitchen_id from public.departments
  where lower(name) = 'kitchen' and location_id = new.location_id limit 1;

  if v_kitchen_id is null then
    raise exception
      'No "Kitchen" department for location % — cannot explode manual sale.', new.location_id
      using errcode = 'no_data_found';
  end if;

  insert into public.inventory_ledger
    (raw_material_id, from_department_id, to_department_id, type, quantity, location_id, transaction_date)
  select ri.raw_material_id, v_kitchen_id, null, 'MANUAL_SALE',
         ri.quantity_needed * new.quantity_sold, new.location_id, new.sale_date
  from public.recipe_ingredients ri
  where ri.recipe_id = new.recipe_id and ri.raw_material_id is not null;
  return new;
end;
$$;

-- Hard-block UPDATE/DELETE on append-only tables.
create or replace function public.prevent_mutation()
returns trigger language plpgsql as $$
begin
  raise exception
    'Table % is append-only: % is not permitted. Post a reversing row instead.',
    tg_table_name, tg_op using errcode = 'restrict_violation';
  return null;
end;
$$;

-- Backstop the security gate: block roles/location_id self-edits unless the
-- caller is a trusted backend (service role → no auth.uid()) or an admin.
create or replace function public.guard_profile_privileges()
returns trigger language plpgsql set search_path = public as $$
begin
  if (new.roles is distinct from old.roles)
     or (new.location_id is distinct from old.location_id) then
    if auth.uid() is not null and not public.is_admin() then
      raise exception 'Not authorized to modify profile roles or location_id.'
        using errcode = 'insufficient_privilege';
    end if;
  end if;
  return new;
end;
$$;

-- =============================================================================
-- SECTION 6: VIEWS + COSTING FUNCTION (security_invoker = on → caller's RLS).
-- ORDER MATTERS: a `language sql` function body is validated at CREATE time, so
-- recipe_cogs() is defined AFTER weighted_average_cost (the view it reads). The
-- view-on-view deps (theoretical_stock→live_stock, stock_count_variance→WAC,
-- recipe_costing→recipe_cogs) likewise come after their sources.
-- =============================================================================

-- live_stock — net on-hand per (location, material, department).
create or replace view public.live_stock with (security_invoker = on) as
with movements as (
  select location_id, raw_material_id, to_department_id   as department_id,  quantity as qty
    from public.inventory_ledger where to_department_id is not null
  union all
  select location_id, raw_material_id, from_department_id as department_id, -quantity as qty
    from public.inventory_ledger where from_department_id is not null
)
select
  rm.location_id, rm.id as raw_material_id, rm.name as raw_material_name,
  rm.category, rm.stock_unit, rm.par_level, m.department_id,
  d.name as department_name,
  coalesce(sum(m.qty), 0) as current_stock,
  (coalesce(sum(m.qty), 0) < rm.par_level) as below_par
from public.raw_materials rm
join movements m          on m.raw_material_id = rm.id and m.location_id = rm.location_id
join public.departments d on d.id = m.department_id and d.location_id = m.location_id
group by rm.location_id, rm.id, rm.name, rm.category, rm.stock_unit, rm.par_level,
         m.department_id, d.name;

-- vendor_dues — purchases (ledger) minus payments, per vendor.
create or replace view public.vendor_dues with (security_invoker = on) as
with purchases as (
  select location_id, vendor_id,
         coalesce(sum(quantity * coalesce(unit_price, 0)), 0) as total_purchased
    from public.inventory_ledger
   where type = 'PURCHASE' and vendor_id is not null
   group by location_id, vendor_id
),
payments as (
  select location_id, vendor_id, coalesce(sum(amount_paid), 0) as total_paid
    from public.vendor_payments group by location_id, vendor_id
)
select
  v.location_id, v.id as vendor_id, v.vendor_code, v.name as vendor_name, v.status,
  coalesce(p.total_purchased, 0) as total_purchased,
  coalesce(pay.total_paid, 0)    as total_paid,
  coalesce(p.total_purchased, 0) - coalesce(pay.total_paid, 0) as outstanding_due
from public.vendors v
left join purchases p   on p.vendor_id   = v.id and p.location_id   = v.location_id
left join payments  pay on pay.vendor_id = v.id and pay.location_id = v.location_id;

-- vendor_master — full vendor row + AUTO stats (paid MTD/YTD, outstanding, last
-- payment/purchase). Nothing hand-typed; powers the Vendor Master sheet + UI.
create or replace view public.vendor_master with (security_invoker = on) as
with pay as (
  select location_id, vendor_id,
         sum(amount_paid) filter (
           where payment_date >= date_trunc('month', (now() at time zone 'Asia/Kolkata'))::date
             and payment_date <= (now() at time zone 'Asia/Kolkata')::date) as paid_mtd,
         sum(amount_paid) filter (
           where payment_date >= date_trunc('year', (now() at time zone 'Asia/Kolkata'))::date
             and payment_date <= (now() at time zone 'Asia/Kolkata')::date) as paid_ytd,
         max(payment_date) as last_payment
    from public.vendor_payments
   group by location_id, vendor_id
),
purch as (
  select location_id, vendor_id,
         max(coalesce(transaction_date::date, (created_at at time zone 'Asia/Kolkata')::date)) as last_purchase
    from public.inventory_ledger
   where type = 'PURCHASE' and vendor_id is not null
   group by location_id, vendor_id
)
select
  v.id, v.location_id, v.vendor_code, v.name, v.nature_of_supply, v.contact_person,
  v.phone, v.alt_phone, v.email, v.category,
  v.bank_name, v.account_number, v.ifsc_code, v.upi_id, v.payment_terms,
  v.address, v.gstin, v.notes,
  coalesce(pay.paid_mtd, 0)       as total_paid_mtd,
  coalesce(pay.paid_ytd, 0)       as total_paid_ytd,
  coalesce(vd.outstanding_due, 0) as outstanding,
  pay.last_payment,
  pu.last_purchase,
  v.created_at                    as first_added,
  v.status,
  v.dormancy_note
from public.vendors v
left join pay   on pay.vendor_id = v.id and pay.location_id = v.location_id
left join purch pu on pu.vendor_id = v.id and pu.location_id = v.location_id
left join public.vendor_dues vd on vd.vendor_id = v.id and vd.location_id = v.location_id;

-- dues_tracker — auto outstanding / status / days-pending for the Dues Tracker.
create or replace view public.dues_tracker with (security_invoker = on) as
select
  id, location_id,
  created_at::date as date_created,
  person_name, amount, reason, linked_date, date_settled,
  settled_amount, settled_mode, notes,
  greatest(amount - settled_amount, 0) as outstanding,
  case when settled_amount >= amount then 'SETTLED'
       when settled_amount > 0       then 'PARTIAL'
       else 'PENDING' end as status,
  case when settled_amount >= amount then null
       else ((now() at time zone 'Asia/Kolkata')::date - coalesce(linked_date, created_at::date)) end as days_pending
from public.dues;

-- weighted_average_cost — total purchase spend / total purchased qty, per material.
create or replace view public.weighted_average_cost with (security_invoker = on) as
select
  rm.location_id, rm.id as raw_material_id, rm.name as raw_material_name, rm.stock_unit,
  coalesce(sum(il.quantity), 0) as total_quantity_purchased,
  coalesce(sum(il.quantity * coalesce(il.unit_price, 0)), 0) as total_spend,
  case when coalesce(sum(il.quantity), 0) > 0
       then sum(il.quantity * coalesce(il.unit_price, 0)) / sum(il.quantity)
       else 0 end as weighted_avg_cost
from public.raw_materials rm
left join public.inventory_ledger il
       on il.raw_material_id = rm.id and il.location_id = rm.location_id and il.type = 'PURCHASE'
group by rm.location_id, rm.id, rm.name, rm.stock_unit;

-- recipe_cogs() — recursive per-portion COGS valued at WAC. Created here, AFTER
-- weighted_average_cost, because its SQL body is validated against that view now.
-- Cycle-safe (path[] guard); compounds each sub-recipe's overhead.
create or replace function public.recipe_cogs(p_recipe_id uuid)
returns numeric language sql stable security invoker set search_path = public as $$
  with recursive exploded as (
    select ri.recipe_id, ri.raw_material_id, ri.sub_recipe_id, ri.quantity_needed,
           array[ri.recipe_id] as path, 1::numeric as multiplier
    from public.recipe_ingredients ri
    where ri.recipe_id = p_recipe_id
    union all
    select child.recipe_id, child.raw_material_id, child.sub_recipe_id, child.quantity_needed,
           e.path || child.recipe_id,
           e.multiplier * e.quantity_needed
             / greatest(coalesce(sub.yield_portions, 1), 1)
             * (1 + coalesce(sub.overhead_percentage, 0) / 100.0) as multiplier
    from exploded e
    join public.recipes sub              on sub.id = e.sub_recipe_id
    join public.recipe_ingredients child on child.recipe_id = e.sub_recipe_id
    where e.sub_recipe_id is not null
      and not (child.recipe_id = any (e.path))
  ),
  batch as (
    select coalesce(sum(e.multiplier * e.quantity_needed
                        * coalesce(wac.weighted_avg_cost, 0)), 0) as batch_cost
    from exploded e
    join public.raw_materials rm on rm.id = e.raw_material_id
    left join public.weighted_average_cost wac
      on wac.raw_material_id = e.raw_material_id and wac.location_id = rm.location_id
    where e.raw_material_id is not null
  )
  select round((b.batch_cost / greatest(r.yield_portions, 1))
               * (1 + coalesce(r.overhead_percentage, 0) / 100.0), 4)
  from public.recipes r cross join batch b
  where r.id = p_recipe_id;
$$;
grant execute on function public.recipe_cogs(uuid) to authenticated;

-- theoretical_stock — intention-revealing alias over live_stock (the book on-hand).
create or replace view public.theoretical_stock with (security_invoker = on) as
select location_id, raw_material_id, raw_material_name, category, stock_unit, par_level,
       department_id, department_name, current_stock as theoretical_qty, below_par
from public.live_stock;

-- stock_count_variance — each manager count paired with its frozen system snapshot.
create or replace view public.stock_count_variance with (security_invoker = on) as
select
  sc.location_id, sc.count_date, sc.department_id, d.name as department_name,
  sc.raw_material_id, rm.name as raw_material_name, rm.stock_unit,
  sc.system_qty, sc.actual_qty, sc.variance, sc.par_level,
  coalesce(wac.weighted_avg_cost, 0) as unit_cost,
  round(sc.variance * coalesce(wac.weighted_avg_cost, 0), 2) as variance_value,
  (sc.actual_qty < sc.par_level) as below_par
from public.stock_counts sc
join public.raw_materials rm on rm.id = sc.raw_material_id and rm.location_id = sc.location_id
join public.departments d    on d.id = sc.department_id and d.location_id = sc.location_id
left join public.weighted_average_cost wac
  on wac.raw_material_id = sc.raw_material_id and wac.location_id = sc.location_id;

-- recipe_costing — selling price, COGS, margin per recipe (recipe_cogs once via LATERAL).
create or replace view public.recipe_costing with (security_invoker = on) as
select
  r.id as recipe_id, r.location_id, r.name as recipe_name, r.category, r.selling_price,
  c.cogs,
  (r.selling_price - c.cogs) as margin_value,
  case when r.selling_price > 0
       then round((r.selling_price - c.cogs) / r.selling_price * 100.0, 2) else 0 end as margin_pct,
  case when r.selling_price > 0
       then round(c.cogs / r.selling_price * 100.0, 2) else 0 end as food_cost_pct
from public.recipes r
cross join lateral (select public.recipe_cogs(r.id) as cogs) c;

-- recipe_sales_volume — portions sold per recipe per day (pos_sales + manual sales).
create or replace view public.recipe_sales_volume with (security_invoker = on) as
select s.location_id, s.recipe_id, s.sold_on, sum(s.quantity)::bigint as portions
from (
  select location_id, recipe_id, (sold_at at time zone 'Asia/Kolkata')::date as sold_on, quantity
    from public.pos_sales
  union all
  select location_id, recipe_id, sale_date as sold_on, quantity_sold as quantity
    from public.manual_sales_log
) s
group by s.location_id, s.recipe_id, s.sold_on;

-- reorder_suggestions — below-PAR materials with suggested order qty, est cost,
-- usual vendor and days-of-cover from trailing-14d SALES_DEPLETION velocity.
create or replace view public.reorder_suggestions with (security_invoker = on) as
with on_hand as (
  select location_id, raw_material_id, sum(current_stock) as current_stock
    from public.live_stock group by location_id, raw_material_id
),
velocity as (
  select location_id, raw_material_id, coalesce(sum(quantity), 0) / 14.0 as daily_usage
    from public.inventory_ledger
   where type = 'SALES_DEPLETION' and created_at >= now() - interval '14 days'
   group by location_id, raw_material_id
)
select
  rm.location_id, rm.id as raw_material_id, rm.name as raw_material_name, rm.stock_unit, rm.par_level,
  coalesce(oh.current_stock, 0) as current_stock,
  greatest(rm.par_level - coalesce(oh.current_stock, 0), 0) as suggested_qty,
  coalesce(wac.weighted_avg_cost, 0) as last_unit_cost,
  round(greatest(rm.par_level - coalesce(oh.current_stock, 0), 0) * coalesce(wac.weighted_avg_cost, 0), 2) as est_cost,
  rm.vendor_id, v.name as vendor_name,
  coalesce(vel.daily_usage, 0) as daily_usage,
  case when coalesce(vel.daily_usage, 0) > 0
       then round(coalesce(oh.current_stock, 0) / vel.daily_usage, 1) else null end as days_cover
from public.raw_materials rm
left join on_hand  oh  on oh.raw_material_id  = rm.id and oh.location_id  = rm.location_id
left join velocity vel on vel.raw_material_id = rm.id and vel.location_id = rm.location_id
left join public.weighted_average_cost wac on wac.raw_material_id = rm.id and wac.location_id = rm.location_id
left join public.vendors v on v.id = rm.vendor_id and v.location_id = rm.location_id
where coalesce(oh.current_stock, 0) < rm.par_level;

-- pos_revenue_expected — expected gross per day (Σ pos_sales × selling_price)
-- to cross-check the manager's hand-entered reconciliation.
create or replace view public.pos_revenue_expected with (security_invoker = on) as
select
  ps.location_id,
  (ps.sold_at at time zone 'Asia/Kolkata')::date as sale_date,
  sum(ps.quantity * r.selling_price) as expected_gross,
  sum(ps.quantity) as items_sold
from public.pos_sales ps
join public.recipes r on r.id = ps.recipe_id and r.location_id = ps.location_id
group by ps.location_id, (ps.sold_at at time zone 'Asia/Kolkata')::date;

-- kitchen_production_view — prepared/sold/wasted + variance + item cost (needs
-- recipe_cogs + weighted_average_cost, defined above).
create or replace view public.kitchen_production_view with (security_invoker = on) as
select
  kp.id, kp.location_id, kp.production_date,
  kp.department_id, d.name as department_name,
  kp.recipe_id, r.name as recipe_name,
  kp.prepared_qty,
  coalesce(rsv.portions, kp.sold_qty)::numeric(14,3) as sold_qty,
  kp.wastage_qty,
  (kp.prepared_qty - coalesce(rsv.portions, kp.sold_qty) - kp.wastage_qty) as variance,
  r.selling_price,
  round(public.recipe_cogs(kp.recipe_id), 2)                 as unit_cost,
  round(kp.wastage_qty * public.recipe_cogs(kp.recipe_id), 2) as wastage_cost,
  kp.notes
from public.kitchen_production kp
join public.recipes r on r.id = kp.recipe_id
left join public.departments d on d.id = kp.department_id and d.location_id = kp.location_id
left join public.recipe_sales_volume rsv
  on rsv.recipe_id = kp.recipe_id and rsv.location_id = kp.location_id
 and rsv.sold_on = kp.production_date
 -- attach sales only to the row in the recipe's OWN department, so a recipe
 -- prepared in two departments never has the full sales broadcast to both.
 and kp.department_id = r.department_id;

-- department_sales — sales (manual + POS) rolled to the item's department.
create or replace view public.department_sales with (security_invoker = on) as
select location_id, department_id, sold_on,
       sum(qty)        as qty_sold,
       sum(sale_value) as sale_value
from (
  select m.location_id, r.department_id, m.sale_date as sold_on,
         m.quantity_sold as qty, m.quantity_sold * r.selling_price as sale_value
    from public.manual_sales_log m
    join public.recipes r on r.id = m.recipe_id and r.location_id = m.location_id
  union all
  select p.location_id, r.department_id,
         (p.sold_at at time zone 'Asia/Kolkata')::date as sold_on,
         p.quantity as qty, p.quantity * r.selling_price as sale_value
    from public.pos_sales p
    join public.recipes r on r.id = p.recipe_id and r.location_id = p.location_id
) s
group by location_id, department_id, sold_on;

-- department_pl — per department: raw issued-in cost (net of inter-dept
-- transfers out), sale revenue, item wastage. Keeps the NULL/Unassigned bucket.
create or replace view public.department_pl with (security_invoker = on) as
with issued as (
  select location_id, department_id, sum(amt) as issued_cost
  from (
    select il.location_id, il.to_department_id as department_id,
           il.quantity * coalesce(wac.weighted_avg_cost, 0) as amt
      from public.inventory_ledger il
      left join public.weighted_average_cost wac
        on wac.raw_material_id = il.raw_material_id and wac.location_id = il.location_id
     where il.type in ('ISSUE_TO_KITCHEN', 'INTER_DEPARTMENT_TRANSFER')
       and il.to_department_id is not null
    union all
    select il.location_id, il.from_department_id as department_id,
           - il.quantity * coalesce(wac.weighted_avg_cost, 0) as amt
      from public.inventory_ledger il
      left join public.weighted_average_cost wac
        on wac.raw_material_id = il.raw_material_id and wac.location_id = il.location_id
     where il.type = 'INTER_DEPARTMENT_TRANSFER' and il.from_department_id is not null
  ) x
  group by location_id, department_id
),
sold as (
  select location_id, department_id,
         sum(sale_value) as sale_value, sum(qty_sold) as items_sold
    from public.department_sales
   group by location_id, department_id
),
waste as (
  select location_id, department_id, sum(wastage_cost) as item_wastage_cost
    from public.kitchen_production_view
   group by location_id, department_id
),
keys as (
  select location_id, department_id from issued
  union select location_id, department_id from sold
  union select location_id, department_id from waste
  union select location_id, id as department_id from public.departments
)
select
  k.location_id, k.department_id, d.name as department_name,
  coalesce(i.issued_cost, 0)       as issued_cost,
  coalesce(s.sale_value, 0)        as sale_value,
  coalesce(s.items_sold, 0)        as items_sold,
  coalesce(w.item_wastage_cost, 0) as item_wastage_cost
from keys k
left join public.departments d on d.id = k.department_id and d.location_id = k.location_id
left join issued i on i.location_id = k.location_id and i.department_id is not distinct from k.department_id
left join sold   s on s.location_id = k.location_id and s.department_id is not distinct from k.department_id
left join waste  w on w.location_id = k.location_id and w.department_id is not distinct from k.department_id;

-- pl_daily — theoretical vs actual COGS + profit per location per day.
create or replace view public.pl_daily with (security_invoker = on) as
with cogs as (
  select
    il.location_id,
    -- business date: MANUAL_SALE carries the sale_date in transaction_date so its
    -- cost lands on the same day as its revenue (backdated sales reconcile).
    coalesce(il.transaction_date, (il.created_at at time zone 'Asia/Kolkata')::date) as d,
    sum(case when il.type in ('SALES_DEPLETION', 'MANUAL_SALE')
             then il.quantity * coalesce(wac.weighted_avg_cost, 0) else 0 end) as theoretical_cogs,
    sum(case when il.type = 'WASTAGE'
             then il.quantity * coalesce(wac.weighted_avg_cost, 0) else 0 end) as wastage_cost,
    sum(case when il.type = 'VARIANCE_RECONCILIATION' and il.from_department_id is not null
             then il.quantity * coalesce(wac.weighted_avg_cost, 0)
             when il.type = 'VARIANCE_RECONCILIATION' and il.to_department_id is not null
             then - il.quantity * coalesce(wac.weighted_avg_cost, 0)
             else 0 end) as variance_cost
  from public.inventory_ledger il
  left join public.weighted_average_cost wac
    on wac.raw_material_id = il.raw_material_id and wac.location_id = il.location_id
  where il.type in ('SALES_DEPLETION', 'MANUAL_SALE', 'WASTAGE', 'VARIANCE_RECONCILIATION')
  group by il.location_id, coalesce(il.transaction_date, (il.created_at at time zone 'Asia/Kolkata')::date)
),
rev as (
  select location_id, sold_on as d,
         sum(sale_value) as revenue, sum(qty_sold) as items_sold
    from public.department_sales
   group by location_id, sold_on
)
select
  coalesce(c.location_id, r.location_id) as location_id,
  coalesce(c.d, r.d)                     as pl_date,
  coalesce(r.revenue, 0)                 as revenue,
  coalesce(r.items_sold, 0)              as items_sold,
  coalesce(c.theoretical_cogs, 0)        as theoretical_cogs,
  coalesce(c.wastage_cost, 0)            as wastage_cost,
  coalesce(c.variance_cost, 0)           as variance_cost,
  coalesce(c.theoretical_cogs, 0) + coalesce(c.wastage_cost, 0)
    + coalesce(c.variance_cost, 0)       as actual_cogs
from cogs c
full join rev r on c.location_id = r.location_id and c.d = r.d;

-- POS analytics (Petpooja pull). security_invoker → inherit pos_orders RLS.
create or replace view public.pos_daily_sales with (security_invoker = on) as
select location_id, order_date,
       count(*) as orders, sum(gross_amount) as gross, sum(discount_amount) as discount,
       sum(tax_amount) as gst, sum(net_amount) as net
  from public.pos_orders where status = 'Success'
 group by location_id, order_date;

create or replace view public.pos_sales_by_channel with (security_invoker = on) as
select o.location_id, o.order_date,
       coalesce(nullif(o.channel, ''), o.order_type, 'Unknown') as channel,
       count(*) as orders, sum(o.gross_amount) as gross, sum(o.net_amount) as net,
       sum(o.tax_amount) as gst,
       round(sum(o.net_amount *
         (1 - coalesce((l.pos_commissions ->>
              coalesce(nullif(o.channel, ''), o.order_type, 'Unknown'))::numeric, 0) / 100)), 2) as net_payout
  from public.pos_orders o
  join public.locations l on l.id = o.location_id
 where o.status = 'Success'
 group by o.location_id, o.order_date,
          coalesce(nullif(o.channel, ''), o.order_type, 'Unknown'), l.pos_commissions;

create or replace view public.pos_daypart with (security_invoker = on) as
select location_id, order_date,
       case when h < 12 then 'Morning' when h < 17 then 'Afternoon'
            when h < 22 then 'Evening' else 'Night' end as daypart,
       count(*) as orders, sum(net_amount) as net
  from (select location_id, order_date, net_amount,
               extract(hour from (sold_at at time zone 'Asia/Kolkata'))::int as h
          from public.pos_orders where status = 'Success' and sold_at is not null) t
 group by location_id, order_date, daypart;

create or replace view public.pos_item_report with (security_invoker = on) as
select ps.location_id, po.order_date, ps.recipe_id, r.name as item_name, r.category,
       sum(ps.quantity) as qty_sold,
       round(sum(ps.quantity) * r.selling_price, 2) as revenue,
       round(sum(ps.quantity) * public.recipe_cogs(ps.recipe_id), 2) as food_cost,
       round(sum(ps.quantity) * (r.selling_price - public.recipe_cogs(ps.recipe_id)), 2) as gross_profit
  from public.pos_sales ps
  join public.pos_orders po on po.location_id = ps.location_id and po.order_key = ps.order_id
  join public.recipes r on r.id = ps.recipe_id
 where po.status = 'Success'
 group by ps.location_id, po.order_date, ps.recipe_id, r.name, r.category, r.selling_price;

-- =============================================================================
-- SECTION 8: TRIGGERS
-- =============================================================================
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users for each row execute function public.handle_new_user();

drop trigger if exists on_manual_sale on public.manual_sales_log;
create trigger on_manual_sale
  after insert on public.manual_sales_log for each row execute function public.handle_manual_sale();

drop trigger if exists trg_block_mutation on public.inventory_ledger;
create trigger trg_block_mutation
  before update or delete on public.inventory_ledger
  for each row execute function public.prevent_mutation();

drop trigger if exists trg_block_mutation on public.vendor_payments;
create trigger trg_block_mutation
  before update or delete on public.vendor_payments
  for each row execute function public.prevent_mutation();

drop trigger if exists trg_guard_profile_privileges on public.profiles;
create trigger trg_guard_profile_privileges
  before update on public.profiles
  for each row execute function public.guard_profile_privileges();

-- Auto-stamp location_id on insert for every scoped table (profiles excluded —
-- provisioned by handle_new_user with an explicit location).
do $$
declare
  t text;
  scoped text[] := array[
    'vendors', 'raw_materials', 'inventory_ledger', 'recipes', 'recipe_ingredients',
    'manual_sales_log', 'vendor_payments', 'daily_sales_reconciliation',
    'petty_cash_expenses', 'unmapped_sales', 'stock_counts', 'pos_sales'
  ];
begin
  foreach t in array scoped loop
    execute format('drop trigger if exists trg_set_location on public.%I;', t);
    execute format(
      'create trigger trg_set_location before insert on public.%I
         for each row execute function public.set_location_id();', t);
  end loop;
end $$;

-- =============================================================================
-- SECTION 9: ROW LEVEL SECURITY
-- =============================================================================
do $$
declare
  t text;
  all_tables text[] := array[
    'organizations', 'locations', 'profiles', 'profile_locations', 'departments', 'vendors',
    'raw_materials', 'inventory_ledger', 'recipes', 'recipe_ingredients',
    'manual_sales_log', 'vendor_payments', 'daily_sales_reconciliation',
    'petty_cash_expenses', 'location_sheets', 'unmapped_sales', 'stock_counts', 'pos_sales', 'dues',
    'kitchen_production'
  ];
begin
  foreach t in array all_tables loop
    execute format('alter table public.%I enable row level security;', t);
  end loop;
end $$;

-- Tenant config: a user sees only their own org / location.
drop policy if exists organizations_select on public.organizations;
create policy organizations_select on public.organizations
  for select to authenticated using (id = public.current_org_id());

drop policy if exists locations_select on public.locations;
create policy locations_select on public.locations
  for select to authenticated using (id in (select public.current_location_ids()));

drop policy if exists locations_update on public.locations;
create policy locations_update on public.locations
  for update to authenticated
  using (id in (select public.current_location_ids()) and public.can_manage_org())
  with check (id in (select public.current_location_ids()) and public.can_manage_org());

-- profiles: read colleagues across visible outlets; update only your own row
-- (roles/location_id are locked by the security gate — see SECTION 10 + trigger).
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
  for select to authenticated using (location_id in (select public.current_location_ids()));
drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- profile_locations: read your own assignments + org managers read org-wide.
-- Writes are service-role only (no policy/grant below).
drop policy if exists profile_locations_select on public.profile_locations;
create policy profile_locations_select on public.profile_locations
  for select to authenticated
  using (
    profile_id = auth.uid()
    or (public.can_manage_org()
        and location_id in (select id from public.locations
                             where organization_id = public.current_org_id()))
  );

-- Mutable operational tables → broad READ (current_location_ids), home-only WRITE.
do $$
declare
  t text;
  mutable text[] := array[
    'departments', 'vendors', 'raw_materials', 'recipes', 'recipe_ingredients',
    'manual_sales_log', 'daily_sales_reconciliation', 'petty_cash_expenses',
    'unmapped_sales', 'stock_counts', 'pos_sales', 'dues', 'kitchen_production'
  ];
begin
  foreach t in array mutable loop
    execute format('drop policy if exists %I_all    on public.%I;', t, t);
    execute format('drop policy if exists %I_select on public.%I;', t, t);
    execute format('drop policy if exists %I_insert on public.%I;', t, t);
    execute format('drop policy if exists %I_update on public.%I;', t, t);
    execute format('drop policy if exists %I_delete on public.%I;', t, t);
    execute format(
      'create policy %I_select on public.%I for select to authenticated
         using (location_id in (select public.current_location_ids()));', t, t);
    execute format(
      'create policy %I_insert on public.%I for insert to authenticated
         with check (location_id in (select public.current_writable_location_ids()));', t, t);
    execute format(
      'create policy %I_update on public.%I for update to authenticated
         using (location_id in (select public.current_writable_location_ids()))
         with check (location_id in (select public.current_writable_location_ids()));', t, t);
    execute format(
      'create policy %I_delete on public.%I for delete to authenticated
         using (location_id in (select public.current_writable_location_ids()));', t, t);
  end loop;
end $$;

-- Append-only tables → SELECT + INSERT only, location-scoped (UPDATE/DELETE blocked).
drop policy if exists inventory_ledger_insert on public.inventory_ledger;
create policy inventory_ledger_insert on public.inventory_ledger
  for insert to authenticated with check (location_id in (select public.current_writable_location_ids()));
drop policy if exists inventory_ledger_select on public.inventory_ledger;
create policy inventory_ledger_select on public.inventory_ledger
  for select to authenticated using (location_id in (select public.current_location_ids()));

drop policy if exists vendor_payments_insert on public.vendor_payments;
create policy vendor_payments_insert on public.vendor_payments
  for insert to authenticated with check (location_id in (select public.current_writable_location_ids()));
drop policy if exists vendor_payments_select on public.vendor_payments;
create policy vendor_payments_select on public.vendor_payments
  for select to authenticated using (location_id in (select public.current_location_ids()));

-- location_sheets → read across visible outlets; org managers manage.
drop policy if exists location_sheets_select on public.location_sheets;
create policy location_sheets_select on public.location_sheets
  for select to authenticated using (location_id in (select public.current_location_ids()));
drop policy if exists location_sheets_admin on public.location_sheets;
create policy location_sheets_admin on public.location_sheets
  for all to authenticated
  using (location_id in (select public.current_location_ids()) and public.can_manage_org())
  with check (location_id in (select public.current_location_ids()) and public.can_manage_org());

-- =============================================================================
-- SECTION 10: GRANTS (auto-expose is disabled; grant explicitly. RLS still rules.)
-- =============================================================================
grant usage on schema public to authenticated;

grant select on public.organizations to authenticated;
-- locations: SECURITY GATE — no organization_id (tenant) rewrites; no secret reads.
grant select (id, organization_id, name, google_spreadsheet_id,
              petpooja_rest_id, pos_commissions, pos_last_synced_at) on public.locations to authenticated;
grant update (name, google_spreadsheet_id)                       on public.locations to authenticated;
grant select on public.pos_orders, public.pos_daily_sales, public.pos_sales_by_channel,
                public.pos_daypart, public.pos_item_report to authenticated;
-- profiles: SECURITY GATE — authenticated may edit ONLY full_name (not roles/location_id),
-- and cannot self-insert/delete (rows are managed by the trigger + auth cascade).
grant select               on public.profiles to authenticated;
grant update (full_name)   on public.profiles to authenticated;
grant select on public.profile_locations to authenticated;  -- writes: service role only
grant select, insert, update, delete on public.departments               to authenticated;
grant select, insert, update, delete on public.vendors                   to authenticated;
grant select, insert, update, delete on public.dues                      to authenticated;
grant select, insert, update, delete on public.kitchen_production         to authenticated;
grant select, insert, update, delete on public.raw_materials             to authenticated;
grant select, insert                 on public.inventory_ledger          to authenticated;
grant select, insert, update, delete on public.recipes                   to authenticated;
grant select, insert, update, delete on public.recipe_ingredients        to authenticated;
grant select, insert, update, delete on public.manual_sales_log          to authenticated;
grant select, insert                 on public.vendor_payments           to authenticated;
grant select, insert, update, delete on public.daily_sales_reconciliation to authenticated;
grant select, insert, update, delete on public.petty_cash_expenses       to authenticated;
grant select, insert, update, delete on public.location_sheets           to authenticated;
grant select, insert, update, delete on public.unmapped_sales            to authenticated;
grant select, insert, update, delete on public.stock_counts              to authenticated;
grant select, insert, update, delete on public.pos_sales                 to authenticated;

grant select on public.live_stock            to authenticated;
grant select on public.vendor_dues           to authenticated;
grant select on public.vendor_master         to authenticated;
grant select on public.dues_tracker          to authenticated;
grant select on public.kitchen_production_view to authenticated;
grant select on public.department_sales      to authenticated;
grant select on public.department_pl         to authenticated;
grant select on public.pl_daily              to authenticated;
grant select on public.weighted_average_cost to authenticated;
grant select on public.theoretical_stock     to authenticated;
grant select on public.stock_count_variance  to authenticated;
grant select on public.recipe_costing        to authenticated;
grant select on public.recipe_sales_volume   to authenticated;
grant select on public.reorder_suggestions   to authenticated;
grant select on public.pos_revenue_expected  to authenticated;

-- Service role (server-only backend; bypasses RLS via the secret key) needs full
-- table access for privileged provisioning (platform console / owner Team). With
-- "auto-expose new tables" disabled it isn't granted automatically — do it here.
grant all privileges on all tables    in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;
grant execute        on all functions in schema public to service_role;
alter default privileges in schema public grant all     on tables    to service_role;
alter default privileges in schema public grant all     on sequences to service_role;
alter default privileges in schema public grant execute on functions to service_role;

-- =============================================================================
-- SECTION 11: REALTIME — stream ledger + POS + counts (guarded against re-runs).
-- =============================================================================
do $$
declare
  t text;
  rt text[] := array['inventory_ledger', 'unmapped_sales', 'stock_counts', 'pos_sales'];
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach t in array rt loop
      if not exists (
        select 1 from pg_publication_tables
        where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
      ) then
        execute format('alter publication supabase_realtime add table public.%I;', t);
      end if;
    end loop;
  end if;
end $$;

-- =============================================================================
-- SECTION 12: BOOTSTRAP — seed one tenant so you aren't locked out.
-- Runs as the SQL-editor role (bypasses RLS). EDIT v_admin_email to YOUR login.
-- The admin profile is matched by email against auth.users, so it survives a
-- fresh signup (no hardcoded uuid). Sign up that email FIRST, then run this.
-- =============================================================================
do $$
declare
  v_admin_email text := 'yeswantsai9@gmail.com';   -- <<< EDIT to your login email
  v_org uuid;
  v_loc uuid;
  v_uid uuid;
begin
  select id into v_loc from public.locations order by created_at limit 1;
  if v_loc is null then
    insert into public.organizations (name) values ('Thrayam Foods') returning id into v_org;
    insert into public.locations (organization_id, name) values (v_org, 'Main Kitchen')
      returning id into v_loc;
  end if;

  -- IDENTITY assigns ids; name is unique per location, so re-runs are no-ops.
  insert into public.departments (name, location_id) values
    ('Store', v_loc), ('Kitchen', v_loc), ('Bar', v_loc), ('Bakery', v_loc)
  on conflict (location_id, name) do nothing;

  select id into v_uid from auth.users where lower(email) = lower(v_admin_email) limit 1;
  if v_uid is not null then
    insert into public.profiles (id, full_name, roles, location_id)
      values (v_uid, 'Administrator', '{1,2,3,4}', v_loc)
    on conflict (id) do update
      set roles = excluded.roles, location_id = excluded.location_id;
  else
    raise notice 'No auth.users row for %, profile NOT created. Sign up first, then re-run.', v_admin_email;
  end if;
end $$;

-- =============================================================================
-- SECTION 12: CROSS-CLIENT SHEET-SYNC LOCK (coalescing distributed lock)
-- Serializes /api/sheets/push per location so concurrent clients can't race on
-- the same spreadsheet. Session advisory locks are unreliable on Supabase's
-- pooled connections, so we use a lock table + SECURITY DEFINER functions. Both
-- functions derive the location from current_location_id() (caller's HOME), so a
-- caller can only ever lock their own outlet. 120s stale timeout = no deadlock.
-- =============================================================================

create table if not exists public.sheet_sync_locks (
  location_id uuid primary key references public.locations(id) on delete cascade,
  locked_at   timestamptz,
  locked_by   uuid,
  token       uuid,
  pending     boolean not null default false
);
alter table public.sheet_sync_locks add column if not exists token uuid;

alter table public.sheet_sync_locks enable row level security;
-- No policies: direct access denied for `authenticated`; all access via the
-- SECURITY DEFINER functions below (which scope to the caller's home location).

drop function if exists public.acquire_sheet_lock();
drop function if exists public.release_sheet_lock();
drop function if exists public.release_sheet_lock(uuid);

-- Returns a fencing TOKEN when acquired; null when a fresh holder has it (sets
-- pending so the holder re-runs) or there is no home location. 300s stale
-- timeout (keep ≥ the platform's max function duration) reclaims a dead holder.
create or replace function public.acquire_sheet_lock()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  loc uuid := public.current_location_id();
  tok uuid := gen_random_uuid();
  got uuid;
begin
  if loc is null then
    return null;
  end if;

  insert into public.sheet_sync_locks (location_id, locked_at, locked_by, token, pending)
  values (loc, now(), auth.uid(), tok, false)
  on conflict (location_id) do update
    set locked_at = now(),
        locked_by = auth.uid(),
        token     = tok,
        pending   = false
    where sheet_sync_locks.locked_at is null
       or sheet_sync_locks.locked_at < now() - interval '300 seconds'
  returning token into got;

  if got is not null then
    return got; -- = tok; we hold the lock with this fencing token
  end if;

  update public.sheet_sync_locks set pending = true where location_id = loc;
  return null;
end;
$$;

-- Release the lock IF the fencing token still matches (we still own it). Returns
-- whether a re-run is needed (a save coalesced onto this run). A no-op (false) if
-- we were taken over as stale — so we never clear another client's lock.
create or replace function public.release_sheet_lock(tok uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  loc uuid := public.current_location_id();
  was_pending boolean;
begin
  if loc is null then
    return false;
  end if;

  select pending into was_pending
    from public.sheet_sync_locks
   where location_id = loc and token = tok
   for update;

  if not found then
    return false; -- taken over (token changed) — do not touch the new holder
  end if;

  update public.sheet_sync_locks
     set locked_at = null, token = null, pending = false
   where location_id = loc and token = tok;

  return coalesce(was_pending, false);
end;
$$;

grant execute on function public.acquire_sheet_lock() to authenticated;
grant execute on function public.release_sheet_lock(uuid) to authenticated;

-- =============================================================================
-- END OF HERO SCHEMA
-- =============================================================================
