-- =============================================================================
-- 0015 — PHASE 1: SCHEMA HARDENING (multi-tenant constraint hygiene)
--
-- Turns three leftover GLOBAL unique constraints into per-location composite
-- uniques, and makes departments.id collision-free across locations:
--
--   departments.name                 (global) -> UNIQUE (location_id, name)
--   vendors.vendor_code              (global) -> UNIQUE (location_id, vendor_code)
--   daily_sales_reconciliation.date  (global) -> UNIQUE (location_id, date)
--   departments.id  int PK           -> GENERATED BY DEFAULT AS IDENTITY (seq > max)
--
-- STRATEGY: per key, ADD composite -> VERIFY -> DROP global, all in ONE
-- transaction (no uniqueness gap). The global drop DISCOVERS the real
-- constraint name from the catalog and RAISEs if it cannot prove the drop
-- happened — it never relies on `DROP CONSTRAINT IF EXISTS <literal>`, which
-- would silently no-op (and report success) on a wrong/renamed constraint.
--
-- Also folds two correctness fixes tied to the above (approved decisions):
--   * handle_manual_sale(): RAISE when the location has no Kitchen department
--     instead of defaulting to the global magic dept id 2 (which could belong
--     to another location once ids are generated).
--   * live_stock / stock_count_variance: join departments on location_id too,
--     so a row can never aggregate against a foreign-location department.
--
-- location_id is already NOT NULL on all three tables (no backfill is possible
-- or needed). The composite uniques are strictly WEAKER than the globals they
-- replace, so existing data cannot violate them.
--
-- RUN ORDER: 0000 -> 0014 -> 0015. Fully idempotent; on a clean DB built from
-- the updated 0000 every step is a guarded no-op.
-- =============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. ADD the per-location composite uniques (named, idempotent).
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_constraint
                 where conrelid = 'public.departments'::regclass
                   and conname  = 'departments_location_id_name_key') then
    alter table public.departments
      add constraint departments_location_id_name_key unique (location_id, name);
  end if;

  if not exists (select 1 from pg_constraint
                 where conrelid = 'public.vendors'::regclass
                   and conname  = 'vendors_location_id_vendor_code_key') then
    alter table public.vendors
      add constraint vendors_location_id_vendor_code_key unique (location_id, vendor_code);
  end if;

  if not exists (select 1 from pg_constraint
                 where conrelid = 'public.daily_sales_reconciliation'::regclass
                   and conname  = 'daily_sales_reconciliation_location_id_date_key') then
    alter table public.daily_sales_reconciliation
      add constraint daily_sales_reconciliation_location_id_date_key unique (location_id, date);
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 2. DROP the GLOBAL single-column uniques. Discover the real constraint name
--    (the one whose key columns are EXACTLY the target column — never the new
--    2-column composite), drop it, then PROVE it is gone or RAISE.
-- ---------------------------------------------------------------------------
do $$
declare
  rec record;
  v_attnum  smallint;
  v_conname text;
begin
  for rec in
    select * from (values
      ('public.departments'::regclass,                'name'::text),
      ('public.vendors'::regclass,                    'vendor_code'),
      ('public.daily_sales_reconciliation'::regclass, 'date')
    ) as v(tbl, col)
  loop
    select attnum into v_attnum
      from pg_attribute
     where attrelid = rec.tbl and attname = rec.col and not attisdropped;

    -- the GLOBAL unique = a UNIQUE constraint whose conkey is exactly {col}.
    select conname into v_conname
      from pg_constraint
     where conrelid = rec.tbl and contype = 'u' and conkey = array[v_attnum];

    if v_conname is not null then
      execute format('alter table %s drop constraint %I', rec.tbl::text, v_conname);
    end if;

    if exists (select 1 from pg_constraint
                where conrelid = rec.tbl and contype = 'u' and conkey = array[v_attnum]) then
      raise exception
        'Phase 1: a single-column global UNIQUE on %.% still exists after the drop attempt',
        rec.tbl::text, rec.col;
    end if;
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 3. departments.id -> GENERATED BY DEFAULT AS IDENTITY. Existing seeded ids
--    (1..4) are preserved; advance the sequence past max(id) so generated ids
--    never collide with them or with a second location's departments.
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_attribute
                 where attrelid = 'public.departments'::regclass
                   and attname = 'id' and attidentity = 'd') then
    alter table public.departments alter column id add generated by default as identity;
  end if;

  if (select max(id) from public.departments) is not null then
    perform setval(
      pg_get_serial_sequence('public.departments', 'id'),
      (select max(id) from public.departments),
      true   -- is_called = true => next nextval() returns max(id) + 1
    );
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 4. handle_manual_sale() — fail loud if the location has no Kitchen dept,
--    instead of defaulting to a global magic dept id.
-- ---------------------------------------------------------------------------
create or replace function public.handle_manual_sale()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_kitchen_id int;
begin
  select id into v_kitchen_id from public.departments
   where lower(name) = 'kitchen' and location_id = new.location_id
   limit 1;

  if v_kitchen_id is null then
    raise exception
      'No "Kitchen" department for location % — cannot explode manual sale.', new.location_id
      using errcode = 'no_data_found';
  end if;

  insert into public.inventory_ledger
    (raw_material_id, from_department_id, to_department_id, type, quantity, location_id)
  select ri.raw_material_id, v_kitchen_id, null, 'MANUAL_SALE',
         ri.quantity_needed * new.quantity_sold, new.location_id
  from public.recipe_ingredients ri
  where ri.recipe_id = new.recipe_id and ri.raw_material_id is not null;
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- 5. Views — match departments on location_id too, so a row can never
--    aggregate against a department owned by another location. Output columns
--    are unchanged, so create-or-replace keeps dependents (theoretical_stock)
--    intact.
-- ---------------------------------------------------------------------------
create or replace view public.live_stock with (security_invoker = on) as
with movements as (
  select location_id, raw_material_id, to_department_id   as department_id,  quantity as qty
    from public.inventory_ledger where to_department_id is not null
  union all
  select location_id, raw_material_id, from_department_id as department_id, -quantity as qty
    from public.inventory_ledger where from_department_id is not null
)
select
  rm.location_id, rm.id as raw_material_id, rm.name as raw_material_name,
  rm.category, rm.stock_unit, rm.par_level, m.department_id,
  d.name as department_name,
  coalesce(sum(m.qty), 0) as current_stock,
  (coalesce(sum(m.qty), 0) < rm.par_level) as below_par
from public.raw_materials rm
join movements m          on m.raw_material_id = rm.id and m.location_id = rm.location_id
join public.departments d on d.id = m.department_id and d.location_id = m.location_id
group by rm.location_id, rm.id, rm.name, rm.category, rm.stock_unit, rm.par_level,
         m.department_id, d.name;

create or replace view public.stock_count_variance with (security_invoker = on) as
select
  sc.location_id, sc.count_date, sc.department_id, d.name as department_name,
  sc.raw_material_id, rm.name as raw_material_name, rm.stock_unit,
  sc.system_qty, sc.actual_qty, sc.variance, sc.par_level,
  coalesce(wac.weighted_avg_cost, 0) as unit_cost,
  round(sc.variance * coalesce(wac.weighted_avg_cost, 0), 2) as variance_value,
  (sc.actual_qty < sc.par_level) as below_par
from public.stock_counts sc
join public.raw_materials rm on rm.id = sc.raw_material_id and rm.location_id = sc.location_id
join public.departments d    on d.id = sc.department_id and d.location_id = sc.location_id
left join public.weighted_average_cost wac
  on wac.raw_material_id = sc.raw_material_id and wac.location_id = sc.location_id;

commit;

-- =============================================================================
-- END 0015 — PHASE 1 SCHEMA HARDENING
-- =============================================================================
